modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="LGPL-3.0"
[[mods]] #mandatory
modId="farmlife" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Farm Life" #mandatory
credits="Tazz, Ninni, Mr. Esuoh" #optional
authors="Coda" #optional
description=''''''